FROM ubuntu:20.04

COPY files/requirements.txt .

RUN apt update && apt install python3-pip libmysqlclient-dev -y && pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 8000

COPY files/main.py .

CMD ["uvicorn", "main:server", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
