name: datascience
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - annotated-types
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - brotli-python
  - bzip2
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cffi
  - charset-normalizer
  - click
  - comm
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - fastapi
  - fqdn
  - h11
  - httptools
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - isoduration
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libexpat
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - liblapack
  - libnsl
  - libopenblas
  - libsodium
  - libsqlite
  - libstdcxx-ng
  - libuuid
  - libuv
  - libzlib
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - numpy
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pydantic
  - pydantic-core
  - pygments
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - stack_data
  - starlette
  - terminado
  - threadpoolctl
  - time
  - tinycss2
  - tk
  - tomli
  - tornado
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - uri-template
  - urllib3
  - uvicorn
  - uvloop
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - xz
  - yaml
  - zeromq
  - zipp
