apiVersion: v1
kind: Service
metadata:
  name: monservicenodeport
spec:
  type: NodePort
  selector:
    app: nginx-deployment
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000